# Hands-on AI Agent: Daily Sync & Team Dispatcher
## Orchestration menggunakan LangChain + Gemini + Google Sheets

**Use case:** Agent membaca project tracker dari Google Sheets, menganalisis progres dan risiko pekerjaan, menyusun action items, lalu membuat **draf email lokal** untuk direview manusia.

### Tujuan pembelajaran
1. Menghubungkan Gemini dengan LangChain.
2. Mengubah fungsi Python menjadi LangChain Tools menggunakan `@tool`.
3. Membuat agent dengan `create_agent()`.
4. Mengamati orchestration: model → tool → tool result → model.
5. Membuat draf email tanpa mengirim email.

### Alur
`Google Sheets → Python Tools → LangChain Agent (Gemini) → Tool Execution → Daily Sync Analysis → Local Email Draft`

**Penting:** Notebook ini tidak mengirim email. Draf hanya disimpan di memori runtime Colab dan ditampilkan untuk direview. Google Sheets dibaca ulang setiap kali tool dipanggil agar agent tidak menggunakan snapshot lama.

**Sebelum mulai:** siapkan Gemini API key dari Google AI Studio dan simpan di Colab Secrets dengan nama `GOOGLE_API_KEY`. Pastikan akun Google yang digunakan memiliki akses baca ke spreadsheet.

## 0. Konfigurasi awal

Notebook ini menggunakan ID spreadsheet dari kode notebook sumber. Jika menggunakan spreadsheet lain, ganti `SPREADSHEET_ID` pada cell konfigurasi.

Worksheet default adalah tab pertama. Nama tab dapat diganti setelah melihat daftar worksheet.

## 1. Instalasi library

In [1]:
%pip -q install -U langchain langchain-google-genai gspread pandas

ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-colab 1.0.0 requires google-auth==2.49.0, but you have google-auth 2.62.0 which is incompatible.
google-colab 1.0.0 requires pandas==2.2.3, but you have pandas 3.1.0 which is incompatible.

## 2. Autentikasi Google Colab dan konfigurasi Google Sheets

In [2]:
from google.colab import auth, userdata
from google.auth import default
import gspread
import pandas as pd
import json
from typing import Optional

auth.authenticate_user()

creds, _ = default()
gc = gspread.authorize(creds)

# ID dari notebook sumber. Ganti jika memakai spreadsheet lain.
SPREADSHEET_ID = "1Wn1QVN5PmjminBDSnJtEnuKmvqSZSUpMGAMczu-e2ME"

spreadsheet = gc.open_by_key(SPREADSHEET_ID)
worksheet_names = [ws.title for ws in spreadsheet.worksheets()]

print("Spreadsheet:", spreadsheet.title)
print("Worksheet tersedia:", worksheet_names)

# Default ke worksheet pertama. Ubah jika tracker ada di tab lain.
WORKSHEET_NAME = worksheet_names[0]
worksheet = spreadsheet.worksheet(WORKSHEET_NAME)
print("Worksheet aktif:", WORKSHEET_NAME)

/usr/local/lib/python3.13/dist-packages/pandas/core/arrays/masked.py:63: UserWarning: Pandas requires version '1.5.0' or newer of 'bottleneck' (version '1.4.2' currently installed).
  from pandas.core import (

Spreadsheet: Project Management
Worksheet tersedia: ['Project Tracker']
Worksheet aktif: Project Tracker

## 3. Definisikan skema kolom dan fungsi membaca tracker

Fungsi ini dipanggil langsung oleh tool. Dengan demikian, data diambil ulang dari Google Sheets setiap kali agent meminta data.

In [3]:
REQUIRED_COLUMNS = [
    "Task ID", "Project", "Department", "Task / Deliverable", "Owner",
    "Priority", "Status", "Progress (%)", "Start Date", "Due Date",
    "Days to Due", "Overdue?", "Last Update", "Blocker / Notes"
]

def load_project_tracker() -> pd.DataFrame:
    """Ambil data terbaru dari worksheet Google Sheets."""
    records = worksheet.get_all_records()
    df = pd.DataFrame(records)

    if df.empty:
        raise ValueError("Worksheet kosong atau tidak memiliki baris data.")

    missing = [col for col in REQUIRED_COLUMNS if col not in df.columns]
    if missing:
        raise ValueError(
            "Kolom wajib tidak ditemukan: " + ", ".join(missing) +
            ". Periksa header pada Google Sheets atau sesuaikan REQUIRED_COLUMNS."
        )

    # Normalisasi kolom teks
    text_cols = [
        "Task ID", "Project", "Department", "Task / Deliverable",
        "Owner", "Priority", "Status", "Overdue?", "Blocker / Notes"
    ]
    for col in text_cols:
        df[col] = df[col].fillna("").astype(str).str.strip()

    # Normalisasi angka progress
    df["Progress (%)"] = pd.to_numeric(
        df["Progress (%)"].astype(str).str.replace("%", "", regex=False),
        errors="coerce"
    )

    # Konversi nilai kosong/NaN agar aman diserialisasi
    df = df.astype(object).where(pd.notna(df), None)
    return df

tasks = load_project_tracker()
print(f"Berhasil membaca {len(tasks)} task.")
display(tasks.head(10))

Berhasil membaca 300 task.

,Task ID,Project,Department,Task / Deliverable,Owner,Priority,Status,Progress (%),Start Date,Due Date,Days to Due,Overdue?,Last Update,Blocker / Notes
0,TASK-001,Sales Performance Analytics,Data & Analytics,Mengumpulkan kebutuhan data,Budi Santoso,Medium,In Progress,79,05-Sep-2026,23-Nov-2026,24,No,24-Okt-2026,Koordinasi lintas tim berlangsung
1,TASK-002,PMO Transformation,Project Management,Menyusun project charter,Citra Amelia,Critical,In Progress,35,28-Agu-2026,03-Nov-2026,4,No,27-Okt-2026,Sedang dikerjakan
2,TASK-003,Support Process Improvement,Customer Success,Memantau SLA respons,Rizky Maulana,Medium,Completed,100,01-Agu-2026,04-Nov-2026,5,No,25-Okt-2026,Selesai sesuai rencana
3,TASK-004,Data Quality Initiative,Data & Analytics,Membersihkan dataset operasional,Kevin Hartono,Medium,Completed,100,13-Agu-2026,20-Nov-2026,21,No,29-Okt-2026,Dokumentasi telah diperbarui
4,TASK-005,Service Delivery Improvement,Operations,Memeriksa checklist operasional,Aldi Wijaya,Low,In Review,91,07-Sep-2026,15-Nov-2026,16,No,29-Okt-2026,Menunggu review stakeholder
5,TASK-006,Enterprise Process Improvement,Project Management,Mengidentifikasi risiko proyek,Kevin Hartono,High,In Progress,45,11-Agu-2026,22-Okt-2026,-8,Yes,25-Okt-2026,Koordinasi lintas tim berlangsung
6,TASK-007,Internal Workflow Automation,Product & Engineering,Menulis unit test,Putri Ananda,Low,In Progress,19,27-Agu-2026,05-Des-2026,36,No,28-Okt-2026,Koordinasi lintas tim berlangsung
7,TASK-008,Digital Marketing Optimization,Marketing & Communications,Menyiapkan materi kampanye,Dimas Saputra,Medium,Completed,100,18-Sep-2026,09-Des-2026,40,No,27-Okt-2026,Selesai sesuai rencana
8,TASK-009,Enterprise Process Improvement,Project Management,Menyiapkan rapat steering committee,Fajar Nugroho,Low,In Progress,50,04-Sep-2026,22-Nov-2026,23,No,23-Okt-2026,Koordinasi lintas tim berlangsung
9,TASK-010,Operational Excellence,Operations,Menyelesaikan tiket internal,Aldi Wijaya,Medium,In Progress,43,03-Sep-2026,26-Nov-2026,27,No,24-Okt-2026,Sedang dikerjakan

## 4. Pemeriksaan data awal

Gunakan pandas untuk memahami kualitas data sebelum agent bekerja. Pemeriksaan ini bersifat deterministik, bukan kesimpulan LLM.

In [4]:
print("Jumlah task:", len(tasks))
print("\nDistribusi status:")
display(tasks["Status"].value_counts(dropna=False).rename_axis("Status").to_frame("Jumlah"))

print("\nDistribusi prioritas:")
display(tasks["Priority"].value_counts(dropna=False).rename_axis("Priority").to_frame("Jumlah"))

print("\nTask ID duplikat:", int(tasks["Task ID"].duplicated().sum()))
print("Task tanpa owner:", int((tasks["Owner"].fillna("").astype(str).str.strip() == "").sum()))
print("Task tanpa blocker/notes:", int((tasks["Blocker / Notes"].fillna("").astype(str).str.strip() == "").sum()))

display(tasks[[
    "Task ID", "Project", "Task / Deliverable", "Owner", "Priority",
    "Status", "Progress (%)", "Due Date", "Days to Due", "Overdue?", "Blocker / Notes"
]].head(10))

Jumlah task: 300

Distribusi status:

             Jumlah
Status
In Progress     127
Completed        60
Not Started      52
In Review        43
Blocked          18

Distribusi prioritas:

          Jumlah
Priority
Medium       157
High          78
Low           39
Critical      26

Task ID duplikat: 0
Task tanpa owner: 0
Task tanpa blocker/notes: 0

,Task ID,Project,Task / Deliverable,Owner,Priority,Status,Progress (%),Due Date,Days to Due,Overdue?,Blocker / Notes
0,TASK-001,Sales Performance Analytics,Mengumpulkan kebutuhan data,Budi Santoso,Medium,In Progress,79,23-Nov-2026,24,No,Koordinasi lintas tim berlangsung
1,TASK-002,PMO Transformation,Menyusun project charter,Citra Amelia,Critical,In Progress,35,03-Nov-2026,4,No,Sedang dikerjakan
2,TASK-003,Support Process Improvement,Memantau SLA respons,Rizky Maulana,Medium,Completed,100,04-Nov-2026,5,No,Selesai sesuai rencana
3,TASK-004,Data Quality Initiative,Membersihkan dataset operasional,Kevin Hartono,Medium,Completed,100,20-Nov-2026,21,No,Dokumentasi telah diperbarui
4,TASK-005,Service Delivery Improvement,Memeriksa checklist operasional,Aldi Wijaya,Low,In Review,91,15-Nov-2026,16,No,Menunggu review stakeholder
5,TASK-006,Enterprise Process Improvement,Mengidentifikasi risiko proyek,Kevin Hartono,High,In Progress,45,22-Okt-2026,-8,Yes,Koordinasi lintas tim berlangsung
6,TASK-007,Internal Workflow Automation,Menulis unit test,Putri Ananda,Low,In Progress,19,05-Des-2026,36,No,Koordinasi lintas tim berlangsung
7,TASK-008,Digital Marketing Optimization,Menyiapkan materi kampanye,Dimas Saputra,Medium,Completed,100,09-Des-2026,40,No,Selesai sesuai rencana
8,TASK-009,Enterprise Process Improvement,Menyiapkan rapat steering committee,Fajar Nugroho,Low,In Progress,50,22-Nov-2026,23,No,Koordinasi lintas tim berlangsung
9,TASK-010,Operational Excellence,Menyelesaikan tiket internal,Aldi Wijaya,Medium,In Progress,43,26-Nov-2026,27,No,Sedang dikerjakan

## 5. Buat Tool 1 — membaca project tracker

Dekorator `@tool` mengubah fungsi Python menjadi tool yang dapat dipilih model. Deskripsi docstring membantu model memahami kapan dan bagaimana tool digunakan.

Tool membaca ulang Google Sheets saat dipanggil dan mendukung filter status, owner, priority, project, department, dan overdue.

In [5]:
from langchain.tools import tool

@tool
def read_project_tracker_tool(
    status: Optional[str] = None,
    owner: Optional[str] = None,
    priority: Optional[str] = None,
    project: Optional[str] = None,
    department: Optional[str] = None,
    overdue_only: bool = False
) -> str:
    """Baca data terbaru dari Google Sheets project tracker.

    Gunakan tool ini sebelum membuat analisis daily sync.
    Filter opsional: status, owner, priority, project, department,
    atau overdue_only=True untuk hanya mengambil task overdue.
    """
    df = load_project_tracker()

    filters = [
        ("Status", status),
        ("Owner", owner),
        ("Priority", priority),
        ("Project", project),
        ("Department", department),
    ]

    for column, value in filters:
        if value:
            df = df[
                df[column].astype(str).str.casefold() ==
                str(value).strip().casefold()
            ]

    if overdue_only:
        overdue_values = {"yes", "ya", "true", "1"}
        df = df[df["Overdue?"].astype(str).str.casefold().isin(overdue_values)]

    records = df.to_dict(orient="records")
    return json.dumps(records, ensure_ascii=False, default=str)

# Uji tool secara langsung sebelum agent digunakan
tracker_preview = read_project_tracker_tool.invoke({})
preview_records = json.loads(tracker_preview)

print("Jumlah task yang dikembalikan tool:", len(preview_records))
print("Contoh record:")
print(json.dumps(preview_records[:1], ensure_ascii=False, indent=2))

Jumlah task yang dikembalikan tool: 300
Contoh record:
[
  {
    "Task ID": "TASK-001",
    "Project": "Sales Performance Analytics",
    "Department": "Data & Analytics",
    "Task / Deliverable": "Mengumpulkan kebutuhan data",
    "Owner": "Budi Santoso",
    "Priority": "Medium",
    "Status": "In Progress",
    "Progress (%)": 79,
    "Start Date": "05-Sep-2026",
    "Due Date": "23-Nov-2026",
    "Days to Due": 24,
    "Overdue?": "No",
    "Last Update": "24-Okt-2026",
    "Blocker / Notes": "Koordinasi lintas tim berlangsung"
  }
]

## 6. Buat Tool 2 — menyimpan draf email lokal

Tool ini **tidak mengirim email** dan tidak terhubung ke Gmail. Penerima ditetapkan oleh pengguna di konfigurasi, bukan dipilih bebas oleh model. Model hanya menyusun subject dan body.

In [6]:
# Ganti alamat ini sebelum menjalankan agent.
TEAM_EMAIL = "team@example.com"

email_drafts = []

@tool
def create_email_draft_tool(subject: str, body: str) -> str:
    """Simpan draf email daily sync secara lokal untuk direview manusia.
    Tool ini tidak mengirim email. Penerima menggunakan TEAM_EMAIL
    yang dikonfigurasi oleh pengguna.
    """
    if not TEAM_EMAIL or TEAM_EMAIL == "team@example.com":
        raise ValueError(
            "Silakan atur TEAM_EMAIL terlebih dahulu pada cell konfigurasi."
        )

    draft = {
        "to": TEAM_EMAIL,
        "subject": subject,
        "body": body,
        "status": "DRAFT_ONLY — belum dikirim"
    }
    email_drafts.append(draft)

    return json.dumps({
        "ok": True,
        "message": "Draf disimpan di runtime notebook. Tidak ada email yang dikirim.",
        "draft_number": len(email_drafts),
        "recipient": TEAM_EMAIL
    }, ensure_ascii=False)

print("Tool email siap. Penerima yang dikonfigurasi:", TEAM_EMAIL)

Tool email siap. Penerima yang dikonfigurasi: team@example.com

## 7. Siapkan Gemini API Key dan model LangChain

Simpan API key pada **Colab Secrets** dengan nama `GOOGLE_API_KEY`. Jika Secrets tidak tersedia, notebook akan meminta key secara tersembunyi.

Model default di bawah dapat diganti sesuai model Gemini yang tersedia pada akun/API key Anda.

In [13]:
import os
from getpass import getpass
from langchain_google_genai import ChatGoogleGenerativeAI

try:
    GOOGLE_API_KEY = userdata.get("GOOGLE_API_KEY")
except Exception:
    GOOGLE_API_KEY = None

if not GOOGLE_API_KEY:
    GOOGLE_API_KEY = getpass("Masukkan GOOGLE_API_KEY: ")

if not GOOGLE_API_KEY:
    raise ValueError("GOOGLE_API_KEY belum diisi.")

os.environ["GOOGLE_API_KEY"] = GOOGLE_API_KEY

# Ganti model jika model ini tidak tersedia untuk API key Anda.
MODEL_NAME = "gemini-3.5-flash-lite"

llm = ChatGoogleGenerativeAI(
    model=MODEL_NAME,
    temperature=0.2
)

# Tes koneksi sederhana
test_response = llm.invoke("Balas hanya dengan: Gemini terhubung.")
print(test_response.content)

/usr/local/lib/python3.13/dist-packages/langchain_google_genai/chat_models.py:3919: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[{'type': 'text', 'text': 'Gemini terhubung.', 'extras': {'signature': 'EmAKXgFpFH0Tb+d5pTXuHhHi+sweUemSLV+u43Pi8D0UwmtrImi4AVUVGObMfZISNVjySyDCyqDBH0bDPgTwwmIjr3tTX9ELQvvyHuiLofKO+1qp2U2EPoZbjwWD6SIVynE='}}]

## 8. Daftarkan tools ke LangChain

Sekarang fungsi Python sudah menjadi LangChain Tools. LangChain membaca nama, deskripsi, dan schema argumen tool untuk membantu model menentukan tool yang relevan.

In [14]:
agent_tools = [
    read_project_tracker_tool,
    create_email_draft_tool
]

for registered_tool in agent_tools:
    print("-", registered_tool.name, ":", registered_tool.description.split("\n")[0])

- read_project_tracker_tool : Baca data terbaru dari Google Sheets project tracker.
- create_email_draft_tool : Simpan draf email daily sync secara lokal untuk direview manusia.

## 9. Bangun agent dan orchestration dengan `create_agent()`

`create_agent()` membangun agent graph yang mengatur siklus:
1. Model menerima instruksi dan konteks.
2. Model memutuskan apakah perlu memanggil tool.
3. LangChain menjalankan tool.
4. Hasil tool dikembalikan kepada model.
5. Model melanjutkan sampai menghasilkan jawaban akhir.

Kita tidak perlu menulis `execute_tool()` dan `run_agent()` secara manual seperti pada implementasi function calling sebelumnya.

In [15]:
from langchain.agents import create_agent

SYSTEM_PROMPT = """
Kamu adalah Daily Sync & Team Dispatcher untuk tim profesional.

SUMBER KEBENARAN
- Google Sheets project tracker adalah sumber kebenaran status pekerjaan.
- Selalu panggil read_project_tracker_tool sebelum membuat kesimpulan.
- Jangan mengarang task, owner, status, progress, tanggal, atau blocker.
- Jika data kosong atau tidak konsisten, nyatakan keterbatasannya.

ANALISIS
- Prioritaskan task Critical dan High.
- Soroti task overdue, task yang mendekati deadline, dan task berstatus Blocked.
- Bedakan blocker yang tercatat pada tracker dari risiko yang kamu simpulkan.
- Susun executive summary, progres, perhatian utama, dan action items per owner.
- Saat menyebut pekerjaan, selalu sertakan Task ID dan nama tugas:
  [TASK-ID] Nama Task.
- Sertakan project, owner, priority, status, progress, dan due date bila tersedia.

DRAF EMAIL
- Setelah analisis selesai, buat subject dan body email daily sync.
- Panggil create_email_draft_tool untuk menyimpan draf.
- Tool tersebut hanya menyimpan draf lokal, bukan mengirim email.
- Jangan pernah mengklaim email sudah dikirim.

GAYA
- Gunakan bahasa Indonesia yang ramah, ringkas, profesional, dan mudah dipindai.
- Jangan menyimpulkan pekerjaan selesai hanya berdasarkan asumsi.
"""

agent = create_agent(
    model=llm,
    tools=agent_tools,
    system_prompt=SYSTEM_PROMPT,
    name="daily_sync_team_dispatcher"
)

print("Agent berhasil dibuat.")

Agent berhasil dibuat.

## 10. Jalankan Daily Sync Agent

Atur penerima email pada cell Tool 2 sebelum menjalankan cell ini. Prompt meminta agent membaca tracker terbaru, menganalisis pekerjaan, lalu menyimpan draf lokal.

In [17]:
# Set a custom TEAM_EMAIL to bypass the default placeholder validation
globals()["TEAM_EMAIL"] = "faransina.rumere@gmail.com"

request = """
Siapkan daily sync berdasarkan project tracker terbaru.

Buat:
1. Executive summary.
2. Ringkasan progres pekerjaan.
3. Daftar task Critical dan High.
4. Task overdue dan task yang deadline-nya paling dekat.
5. Task Blocked dan blocker yang tercatat.
6. Action items berdasarkan owner, lengkap dengan Task ID.

Setelah analisis selesai, siapkan draf email daily sync.
Jangan mengirim email.
"""

result = agent.invoke({
    "messages": [
        {"role": "user", "content": request}
    ]
})

final_message = result["messages"][-1]
print(final_message.content)

/usr/local/lib/python3.13/dist-packages/langchain_google_genai/chat_models.py:3919: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
/usr/local/lib/python3.13/dist-packages/langchain_google_genai/chat_models.py:3919: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
/usr/local/lib/python3.13/dist-packages/langchain_google_genai/chat_models.py:3919: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[{'type': 'text', 'text': 'Berikut adalah hasil analisis *Daily Sync* dan dispatch tim berdasarkan data terbaru dari Google Sheets *project tracker*:\n\n---\n\n### 1. Executive Summary\nSecara umum, kegiatan operasional dan proyek tim berjalan dengan baik; banyak task yang telah mencapai status *Completed* atau *In Review*. Namun, perhatian manajerial mendesak diperlukan untuk menangani **task berstatus Blocked** serta **task yang sudah Overdue** (terutama dengan prioritas *Critical* dan *High*). Eskalasi lintas departemen diperlukan untuk menghapus hambatan (*blocker*) terkait dependensi vendor dan persetujuan manajemen.\n\n---\n\n### 2. Ringkasan Progres Pekerjaan\n* **Total Task Tercatat:** 300 task di berbagai departemen.\n* **Status Penyelesaian:** Sejumlah besar task telah selesai (*Completed*) atau berada di tahap akhir (*In Review*).\n* **Area Perhatian:** Sejumlah task mengalami penundaan (*overdue*) dari tenggat waktu aslinya dan beberapa task tertahan (*blocked*) karena menunggu data, persetujuan, atau dependensi vendor.\n\n---\n\n### 3. Daftar Task Critical dan High\nBerikut adalah ringkasan task prioritas *Critical* dan *High* yang aktif dalam sistem:\n* **[TASK-002] Menyusun project charter** (*PMO Transformation*) | Owner: Citra Amelia | Priority: **Critical** | Status: In Progress (35%) | Due Date: 03-Nov-2026\n* **[TASK-006] Mengidentifikasi risiko proyek** (*Enterprise Process Improvement*) | Owner: Kevin Hartono | Priority: **High** | Status: In Progress (45%) | Due Date: 22-Okt-2026 (**Overdue**)\n* **[TASK-011] Memperbarui database pelatihan** (*Talent Acquisition Sprint*) | Owner: Dewi Lestari | Priority: **Critical** | Status: Not Started (0%) | Due Date: 06-Des-2026\n* **[TASK-013] Melakukan rekonsiliasi biaya** (*Procurement Efficiency*) | Owner: Rafi Hidayat | Priority: **Critical** | Status: In Progress (43%) | Due Date: 30-Nov-2026\n* **[TASK-014] Meninjau kontrak vendor** (*Vendor Management*) | Owner: Andi Pratama | Priority: **High** | Status: In Progress (77%) | Due Date: 27-Okt-2026 (**Overdue**)\n* **[TASK-019] Mengumpulkan kebutuhan data** (*Business Intelligence Dashboard*) | Owner: Lia Maharani | Priority: **Critical** | Status: Completed (100%) | Due Date: 07-Nov-2026\n* **[TASK-021] Menindaklanjuti permintaan pelanggan** (*Client Onboarding*) | Owner: Intan Permata | Priority: **High** | Status: In Progress (23%) | Due Date: 27-Okt-2026 (**Overdue**)\n* **[TASK-033] Memperbarui dokumentasi teknis** (*Platform Reliability*) | Owner: Rizky Maulana | Priority: **Critical** | Status: Not Started (0%) | Due Date: 25-Okt-2026 (**Overdue**)\n* **[TASK-079] Memproses reimbursement** (*Budget Control Initiative*) | Owner: Tania Wibowo | Priority: **Critical** | Status: In Progress (15%) | Due Date: 29-Nov-2026\n* **[TASK-114] Memperbarui database pelatihan** (*Performance Management*) | Owner: Rafi Hidayat | Priority: **Critical** | Status: In Progress (63%) | Due Date: 29-Nov-2026\n* **[TASK-120] Melakukan rekonsiliasi biaya** (*Procurement Efficiency*) | Owner: Tania Wibowo | Priority: **Critical** | Status: Not Started (0%) | Due Date: 12-Des-2026\n* **[TASK-137] Mendokumentasikan data dictionary** (*Data Quality Initiative*) | Owner: Budi Santoso | Priority: **Critical** | Status: In Progress (74%) | Due Date: 16-Nov-2026\n* **[TASK-152] Menjadwalkan wawancara kandidat** (*Performance Management*) | Owner: Rizky Maulana | Priority: **Critical** | Status: In Progress (70%) | Due Date: 07-Des-2026\n* **[TASK-156] Memperbarui database pelatihan** (*Performance Management*) | Owner: Budi Santoso | Priority: **Critical** | Status: In Review (91%) | Due Date: 30-Nov-2026\n* **[TASK-159] Membuat wireframe fitur** (*Platform Reliability*) | Owner: Siti Rahma | Priority: **Critical** | Status: In Progress (35%) | Due Date: 25-Nov-2026\n* **[TASK-176] Mengembangkan API endpoint** (*Platform Reliability*) | Owner: Budi Santoso | Priority: **Critical** | Status: Completed (100%) | Due Date: 09-Nov-2026\n* **[TASK-180] Menganalisis feedback pelanggan** (*Support Process Improvement*) | Owner: Putri Ananda | Priority: **Critical** | Status: In Progress (59%) | Due Date: 19-Nov-2026\n* **[TASK-186] Menyusun laporan komunikasi** (*Corporate Communications*) | Owner: Dimas Saputra | Priority: **Critical** | Status: Not Started (0%) | Due Date: 31-Okt-2026\n* **[TASK-190] Melakukan code review** (*Customer Portal Revamp*) | Owner: Dimas Saputra | Priority: **Critical** | Status: Not Started (0%) | Due Date: 12-Nov-2026\n* **[TASK-197] Menyusun kalender konten** (*Corporate Communications*) | Owner: Dimas Saputra | Priority: **Critical** | Status: In Review (93%) | Due Date: 04-Nov-2026\n* **[TASK-223] Menyusun kalender konten** (*Digital Marketing Optimization*) | Owner: Fajar Nugroho | Priority: **Critical** | Status: In Review (82%) | Due Date: 10-Des-2026\n* **[TASK-251] Menyusun laporan komunikasi** (*Corporate Communications*) | Owner: Kevin Hartono | Priority: **Critical** | Status: Blocked (56%) | Due Date: 18-Nov-2026\n* **[TASK-279] Melakukan deployment ke production** (*Internal Workflow Automation*) | Owner: Kevin Hartono | Priority: **Critical** | Status: Blocked (50%) | Due Date: 20-Okt-2026 (**Overdue**)\n* **[TASK-289] Menyusun definisi KPI** (*Data Quality Initiative*) | Owner: Rizky Maulana | Priority: **Critical** | Status: Completed (100%) | Due Date: 21-Nov-2026\n* **[TASK-292] Melakukan rekonsiliasi data** (*Sales Performance Analytics*) | Owner: Fajar Nugroho | Priority: **Critical** | Status: Not Started (0%) | Due Date: 05-Nov-2026\n\n---\n\n### 4. Task Overdue dan Deadline Terdekat\n* **Task Overdue Utama:**\n  * **[TASK-006] Mengidentifikasi risiko proyek** (Kevin Hartono) – Overdue 8 hari\n  * **[TASK-014] Meninjau kontrak vendor** (Andi Pratama) – Overdue 3 hari\n  * **[TASK-021] Menindaklanjuti permintaan pelanggan** (Intan Permata) – Overdue 3 hari\n  * **[TASK-033] Memperbarui dokumentasi teknis** (Rizky Maulana) – Overdue 5 hari\n  * **[TASK-279] Melakukan deployment ke production** (Kevin Hartono) – Overdue (Due: 20-Okt-2026)\n* **Deadline Terdekat (<= 3 hari ke depan):**\n  * **[TASK-022] Memperbarui knowledge base** (Kevin Hartono) – Due: 31-Okt-2026\n  * **[TASK-050] Memperbarui cash-flow forecast** (Budi Santoso) – Due: 31-Okt-2026\n  * **[TASK-144] Menyiapkan staging release** (Fajar Nugroho) – Due: 01-Nov-2026\n  * **[TASK-150] Memperbarui tracking anggaran** (Intan Permata) – Due: 01-Nov-2026\n  * **[TASK-186] Menyusun laporan komunikasi** (Dimas Saputra) – Due: 31-Okt-2026\n  * **[TASK-220] Menyiapkan rapat steering committee** (Rizky Maulana) – Due: 02-Nov-2026\n  * **[TASK-260] Memvalidasi kualitas data** (Tania Wibowo) – Due: 01-Nov-2026\n\n---\n\n### 5. Task Blocked dan Blocker yang Tercatat\nBerikut adalah task yang berstatus *Blocked* beserta catatan kendala pada tracker:\n* **[TASK-053] Mengumpulkan feedback karyawan** (Intan Permata) – *Blocker:* Dependensi vendor belum selesai\n* **[TASK-069] Menganalisis performa kampanye** (Putri Ananda) – *Blocker:* Dependensi vendor belum selesai\n* **[TASK-113] Membandingkan penawaran vendor** (Andi Pratama) – *Blocker:* Menunggu data dari tim terkait\n* **[TASK-124] Memverifikasi invoice vendor** (Andi Pratama) – *Blocker:* Menunggu data dari tim terkait\n* **[TASK-125] Memeriksa checklist operasional** (Kevin Hartono) – *Blocker:* Dependensi vendor belum selesai\n* **[TASK-160] Mengidentifikasi bottleneck proses** (Siti Rahma) – *Blocker:* Menunggu persetujuan manajer\n* **[TASK-161] Memperbarui tracking anggaran** (Dimas Saputra) – *Blocker:* Menunggu data dari tim terkait\n* **[TASK-181] Menulis unit test** (Kevin Hartono) – *Blocker:* Dependensi vendor belum selesai\n* **[TASK-218] Menyusun laporan komunikasi** (Maya Anggraini) – *Blocker:* Menunggu data dari tim terkait\n* **[TASK-250] Mengumpulkan feedback karyawan** (Yoga Firmansyah) – *Blocker:* Dependensi vendor belum selesai\n* **[TASK-251] Menyusun laporan komunikasi** (Kevin Hartono) – *Blocker:* Menunggu persetujuan manajer\n* **[TASK-271] Menyusun rencana tindak lanjut akun** (Maya Anggraini) – *Blocker:* Menunggu data dari tim terkait\n* **[TASK-279] Melakukan deployment ke production** (Kevin Hartono) – *Blocker:* Menunggu data dari tim terkait\n\n---\n\n### 6. Action Items Berdasarkan Owner\n* **Kevin Hartono:**\n  * **[TASK-006]** Segera eskalasi dan selesaikan identifikasi risiko proyek yang overdue.\n  * **[TASK-251] & [TASK-279]** Koordinasikan kendala persetujuan manajer dan data yang tertunda untuk membuka blokir task kritikal ini.\n* **Andi Pratama:**\n  * **[TASK-014]** Selesaikan peninjauan kontrak vendor yang sudah melewati tenggat waktu.\n  * **[TASK-113] & [TASK-124]** Lakukan follow-up aktif untuk mendapatkan data yang dibutuhkan dari tim terkait.\n* **Rizky Maulana:**\n  * **[TASK-033]** Segera inisiasi dan kejar ketertinggalan pembaruan dokumentasi teknis.\n* **Intan Permata:**\n  * **[TASK-021]** Prioritaskan tindak lanjut permintaan pelanggan yang sudah *overdue*.\n* **Putri Ananda & Siti Rahma:**\n  * **[TASK-069], [TASK-160], [TASK-180]** Pantau dan selesaikan blocker terkait persetujuan manajer serta dependensi vendor.\n* **Dimas Saputra:**\n  * **[TASK-186] & [TASK-190]** Perhatikan tenggat waktu terdekat untuk task kritis yang belum dimulai.\n\n---\n\n### Draf Email Daily Sync\nDraf email telah berhasil disimpan secara lokal menggunakan `create_email_draft_tool` (tidak ada email yang dikirim secara otomatis). Anda dapat meninjau draf tersebut sebelum didistribusikan secara manual.', 'extras': {'signature': 'EmAKXgFpFH0ToXDFcReSIYhKGc9YH/z/VzT76UTyPIMZeetwqZEtcN5OXta9UYCZibbg+xWgsfMN5guhtX7vMHtMvF9+jxjleHcmxnSrND4rDRphc9mMwdBExguw5y+0ce0='}}]

## 11. Amati orchestration dan tool calls

Cell ini menampilkan jejak pesan yang dikembalikan agent. Perhatikan:
- `AIMessage` dengan `tool_calls`: model meminta tool dijalankan.
- `ToolMessage`: hasil eksekusi tool.
- `AIMessage` berikutnya: model memproses hasil tool atau memberi jawaban akhir.

Urutan pesan aktual dapat berbeda tergantung keputusan model.

In [18]:
from langchain_core.messages import AIMessage, ToolMessage

for idx, message in enumerate(result["messages"], start=1):
    print("\n" + "=" * 72)
    print(f"MESSAGE {idx}: {type(message).__name__}")

    if isinstance(message, AIMessage) and message.tool_calls:
        for call in message.tool_calls:
            print("TOOL CALL:", call["name"])
            print("ARGUMENTS:", call["args"])

    elif isinstance(message, ToolMessage):
        print("TOOL NAME:", message.name)
        print("TOOL OUTPUT:")
        print(str(message.content)[:3000])

    else:
        content = message.content
        print("CONTENT:")
        print(content if isinstance(content, str) else str(content)[:3000])

========================================================================
MESSAGE 1: HumanMessage
CONTENT:

Siapkan daily sync berdasarkan project tracker terbaru.

Buat:
1. Executive summary.
2. Ringkasan progres pekerjaan.
3. Daftar task Critical dan High.
4. Task overdue dan task yang deadline-nya paling dekat.
5. Task Blocked dan blocker yang tercatat.
6. Action items berdasarkan owner, lengkap dengan Task ID.

Setelah analisis selesai, siapkan draf email daily sync.
Jangan mengirim email.


========================================================================
MESSAGE 2: AIMessage
TOOL CALL: read_project_tracker_tool
ARGUMENTS: {}

========================================================================
MESSAGE 3: ToolMessage
TOOL NAME: read_project_tracker_tool
TOOL OUTPUT:
[{"Task ID": "TASK-001", "Project": "Sales Performance Analytics", "Department": "Data & Analytics", "Task / Deliverable": "Mengumpulkan kebutuhan data", "Owner": "Budi Santoso", "Priority": "Medium", "Status": "In Progress", "Progress (%)": 79, "Start Date": "05-Sep-2026", "Due Date": "23-Nov-2026", "Days to Due": 24, "Overdue?": "No", "Last Update": "24-Okt-2026", "Blocker / Notes": "Koordinasi lintas tim berlangsung"}, {"Task ID": "TASK-002", "Project": "PMO Transformation", "Department": "Project Management", "Task / Deliverable": "Menyusun project charter", "Owner": "Citra Amelia", "Priority": "Critical", "Status": "In Progress", "Progress (%)": 35, "Start Date": "28-Agu-2026", "Due Date": "03-Nov-2026", "Days to Due": 4, "Overdue?": "No", "Last Update": "27-Okt-2026", "Blocker / Notes": "Sedang dikerjakan"}, {"Task ID": "TASK-003", "Project": "Support Process Improvement", "Department": "Customer Success", "Task / Deliverable": "Memantau SLA respons", "Owner": "Rizky Maulana", "Priority": "Medium", "Status": "Completed", "Progress (%)": 100, "Start Date": "01-Agu-2026", "Due Date": "04-Nov-2026", "Days to Due": 5, "Overdue?": "No", "Last Update": "25-Okt-2026", "Blocker / Notes": "Selesai sesuai rencana"}, {"Task ID": "TASK-004", "Project": "Data Quality Initiative", "Department": "Data & Analytics", "Task / Deliverable": "Membersihkan dataset operasional", "Owner": "Kevin Hartono", "Priority": "Medium", "Status": "Completed", "Progress (%)": 100, "Start Date": "13-Agu-2026", "Due Date": "20-Nov-2026", "Days to Due": 21, "Overdue?": "No", "Last Update": "29-Okt-2026", "Blocker / Notes": "Dokumentasi telah diperbarui"}, {"Task ID": "TASK-005", "Project": "Service Delivery Improvement", "Department": "Operations", "Task / Deliverable": "Memeriksa checklist operasional", "Owner": "Aldi Wijaya", "Priority": "Low", "Status": "In Review", "Progress (%)": 91, "Start Date": "07-Sep-2026", "Due Date": "15-Nov-2026", "Days to Due": 16, "Overdue?": "No", "Last Update": "29-Okt-2026", "Blocker / Notes": "Menunggu review stakeholder"}, {"Task ID": "TASK-006", "Project": "Enterprise Process Improvement", "Department": "Project Management", "Task / Deliverable": "Mengidentifikasi risiko proyek", "Owner": "Kevin Hartono", "Priority": "High", "Status": "In Progress", "Progress (%)": 45, "Start Date": "11-Agu-2026", "Due Date": "22-Okt-2026", "Days to Due": -8, "Overdue?": "Yes", "Last Update": "25-Okt-2026", "Blocker / Notes": "Koordinasi lintas tim berlangsung"}, {"Task ID": "TASK-007", "Project": "Internal Workflow Automation", "Department": "Product & Engineering", "Task / Deliverable": "Menulis unit test", "Owner": "Putri Ananda", "Priority": "Low", "Status": "In Progress", "Progress (%)": 19, "Start Date": "27-Agu-2026", "Due Date": "05-Des-2026", "Days to Due": 36, "Overdue?": "No", "Last Update": "28-Okt-2026", "Blocker / Notes": "Koordinasi lintas tim berlangsung"}, {"Task ID": "TASK-008", "Project": "Digital Marketing Optimization", "Department": "

========================================================================
MESSAGE 4: AIMessage
TOOL CALL: create_email_draft_tool
ARGUMENTS: {'subject': 'Daily Sync & Action Items - Progres & Task Prioritas', 'body': 'Halo Tim,\n\nBerikut adalah rangkuman Daily Sync berdasarkan Google Sheets project tracker terbaru.\n\n1. EXECUTIVE SUMMARY\nSecara keseluruhan, progres tim berjalan dengan baik dengan banyak task yang sudah berstatus Completed atau In Review. Namun, terdapat perhatian khusus pada beberapa task berprioritas Critical dan High yang berstatus Blocked maupun Overdue, yang memerlukan eskalasi dan tindakan cepat dari owner terkait.\n\n2. RINGKASAN PROGRES PEKERJAAN\n- Total Task Tercatat: 300 task\n- Completed: Sejumlah task telah diselesaikan sesuai target di berbagai departemen.\n- In Progress / In Review: Mayoritas task berjalan sesuai rencana atau menunggu review stakeholder.\n- Blocked & Overdue: Memerlukan intervensi segera untuk mencegah dampak lanjutan pada timeline proyek.\n\n3. DAFTAR TASK CRITICAL DAN HIGH\nBerikut adalah daftar task dengan prioritas Critical dan High yang membutuhkan perhatian:\n- [TASK-002] Menyusun project charter (PMO Transformation) | Owner: Citra Amelia | Priority: Critical | Status: In Progress | Progress: 35% | Due Date: 03-Nov-2026\n- [TASK-006] Mengidentifikasi risiko proyek (Enterprise Process Improvement) | Owner: Kevin Hartono | Priority: High | Status: In Progress | Progress: 45% | Due Date: 22-Okt-2026 (Overdue)\n- [TASK-011] Memperbarui database pelatihan (Talent Acquisition Sprint) | Owner: Dewi Lestari | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 06-Des-2026\n- [TASK-013] Melakukan rekonsiliasi biaya (Procurement Efficiency) | Owner: Rafi Hidayat | Priority: Critical | Status: In Progress | Progress: 43% | Due Date: 30-Nov-2026\n- [TASK-014] Meninjau kontrak vendor (Vendor Management) | Owner: Andi Pratama | Priority: High | Status: In Progress | Progress: 77% | Due Date: 27-Okt-2026 (Overdue)\n- [TASK-019] Mengumpulkan kebutuhan data (Business Intelligence Dashboard) | Owner: Lia Maharani | Priority: Critical | Status: Completed | Progress: 100% | Due Date: 07-Nov-2026\n- [TASK-021] Menindaklanjuti permintaan pelanggan (Client Onboarding) | Owner: Intan Permata | Priority: High | Status: In Progress | Progress: 23% | Due Date: 27-Okt-2026 (Overdue)\n- [TASK-033] Memperbarui dokumentasi teknis (Platform Reliability) | Owner: Rizky Maulana | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 25-Okt-2026 (Overdue)\n- [TASK-079] Memproses reimbursement (Budget Control Initiative) | Owner: Tania Wibowo | Priority: Critical | Status: In Progress | Progress: 15% | Due Date: 29-Nov-2026\n- [TASK-114] Memperbarui database pelatihan (Performance Management) | Owner: Rafi Hidayat | Priority: Critical | Status: In Progress | Progress: 63% | Due Date: 29-Nov-2026\n- [TASK-120] Melakukan rekonsiliasi biaya (Procurement Efficiency) | Owner: Tania Wibowo | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 12-Des-2026\n- [TASK-137] Mendokumentasikan data dictionary (Data Quality Initiative) | Owner: Budi Santoso | Priority: Critical | Status: In Progress | Progress: 74% | Due Date: 16-Nov-2026\n- [TASK-152] Menjadwalkan wawancara kandidat (Performance Management) | Owner: Rizky Maulana | Priority: Critical | Status: In Progress | Progress: 70% | Due Date: 07-Des-2026\n- [TASK-156] Memperbarui database pelatihan (Performance Management) | Owner: Budi Santoso | Priority: Critical | Status: In Review | Progress: 91% | Due Date: 30-Nov-2026\n- [TASK-159] Membuat wireframe fitur (Platform Reliability) | Owner: Siti Rahma | Priority: Critical | Status: In Progress | Progress: 35% | Due Date: 25-Nov-2026\n- [TASK-176] Mengembangkan API endpoint (Platform Reliability) | Owner: Budi Santoso | Priority: Critical | Status: Completed | Progress: 100% | Due Date: 09-Nov-2026\n- [TASK-180] Menganalisis feedback pelanggan (Support Process Improvement) | Owner: Putri Ananda | Priority: Critical | Status: In Progress | Progress: 59% | Due Date: 19-Nov-2026\n- [TASK-186] Menyusun laporan komunikasi (Corporate Communications) | Owner: Dimas Saputra | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 31-Okt-2026\n- [TASK-190] Melakukan code review (Customer Portal Revamp) | Owner: Dimas Saputra | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 12-Nov-2026\n- [TASK-197] Menyusun kalender konten (Corporate Communications) | Owner: Dimas Saputra | Priority: Critical | Status: In Review | Progress: 93% | Due Date: 04-Nov-2026\n- [TASK-223] Menyusun kalender konten (Digital Marketing Optimization) | Owner: Fajar Nugroho | Priority: Critical | Status: In Review | Progress: 82% | Due Date: 10-Des-2026\n- [TASK-251] Menyusun laporan komunikasi (Corporate Communications) | Owner: Kevin Hartono | Priority: Critical | Status: Blocked | Progress: 56% | Due Date: 18-Nov-2026\n- [TASK-279] Melakukan deployment ke production (Internal Workflow Automation) | Owner: Kevin Hartono | Priority: Critical | Status: Blocked | Progress: 50% | Due Date: 20-Oktober-2026 (Overdue)\n- [TASK-289] Menyusun definisi KPI (Data Quality Initiative) | Owner: Rizky Maulana | Priority: Critical | Status: Completed | Progress: 100% | Due Date: 21-Nov-2026\n- [TASK-292] Melakukan rekonsiliasi data (Sales Performance Analytics) | Owner: Fajar Nugroho | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 05-Nov-2026\n\n4. TASK OVERDUE & DEADLINE TERDEKAT\n- Task Overdue Utama yang Perlu Tindak Lanjut Segera:\n  • [TASK-006] Mengidentifikasi risiko proyek (Kevin Hartono) - Overdue 8 hari\n  • [TASK-014] Meninjau kontrak vendor (Andi Pratama) - Overdue 3 hari\n  • [TASK-021] Menindaklanjuti permintaan pelanggan (Intan Permata) - Overdue 3 hari\n  • [TASK-033] Memperbarui dokumentasi teknis (Rizky Maulana) - Overdue 5 hari\n  • [TASK-279] Melakukan deployment ke production (Kevin Hartono) - Overdue (Due: 20-Okt-2026)\n- Task Deadline Terdekat (<= 3 hari ke depan):\n  • [TASK-022] Memperbarui knowledge base (Kevin Hartono) - Due: 31-Okt-2026\n  • [TASK-050] Memperbarui cash-flow forecast (Budi Santoso) - Due: 31-Okt-2026\n  • [TASK-144] Menyiapkan staging release (Fajar Nugroho) - Due: 01-Nov-2026\n  • [TASK-150] Memperbarui tracking anggaran (Intan Permata) - Due: 01-Nov-2026\n  • [TASK-186] Menyusun laporan komunikasi (Dimas Saputra) - Due: 31-Okt-2026\n  • [TASK-220] Menyiapkan rapat steering committee (Rizky Maulana) - Due: 02-Nov-2026\n  • [TASK-260] Memvalidasi kualitas data (Tania Wibowo) - Due: 01-Nov-2026\n\n5. TASK BLOCKED DAN BLOCKER YANG TERCATAT\nBerikut task yang berstatus Blocked beserta keterangan blocker pada tracker:\n- [TASK-053] Mengumpulkan feedback karyawan (Intan Permata) | Blocker: Dependensi vendor belum selesai\n- [TASK-069] Menganalisis performa kampanye (Putri Ananda) | Blocker: Dependensi vendor belum selesai\n- [TASK-113] Membandingkan penawaran vendor (Andi Pratama) | Blocker: Menunggu data dari tim terkait\n- [TASK-124] Memverifikasi invoice vendor (Andi Pratama) | Blocker: Menunggu data dari tim terkait\n- [TASK-125] Memeriksa checklist operasional (Kevin Hartono) | Blocker: Dependensi vendor belum selesai\n- [TASK-160] Mengidentifikasi bottleneck proses (Siti Rahma) | Blocker: Menunggu persetujuan manajer\n- [TASK-161] Memperbarui tracking anggaran (Dimas Saputra) | Blocker: Menunggu data dari tim terkait\n- [TASK-181] Menulis unit test (Kevin Hartono) | Blocker: Dependensi vendor belum selesai\n- [TASK-218] Menyusun laporan komunikasi (Maya Anggraini) | Blocker: Menunggu data dari tim terkait\n- [TASK-250] Mengumpulkan feedback karyawan (Yoga Firmansyah) | Blocker: Dependensi vendor belum selesai\n- [TASK-251] Menyusun laporan komunikasi (Kevin Hartono) | Blocker: Menunggu persetujuan manajer\n- [TASK-271] Menyusun rencana tindak lanjut akun (Maya Anggraini) | Blocker: Menunggu data dari tim terkait\n- [TASK-279] Melakukan deployment ke production (Kevin Hartono) | Blocker: Menunggu data dari tim terkait\n\n6. ACTION ITEMS PER OWNER\n- **Citra Amelia**:\n  • [TASK-002] Menyusun project charter (Critical) - Lanjutkan progres (35%, Due: 03-Nov-2026).\n- **Kevin Hartono**:\n  • [TASK-006] Mengidentifikasi risiko proyek (High, Overdue) - Segera selesaikan task yang tertunda.\n  • [TASK-251] Menyusun laporan komunikasi (Critical, Blocked) - Koordinasikan persetujuan manajer.\n  • [TASK-279] Melakukan deployment ke production (Critical, Blocked, Overdue) - Eskalasi kendala data untuk deployment.\n- **Andi Pratama**:\n  • [TASK-014] Meninjau kontrak vendor (High, Overdue) - Selesaikan peninjauan segera.\n  • [TASK-113] & [TASK-124] (High/Low, Blocked) - Tindak lanjuti kelengkapan data dari tim terkait.\n- **Rizky Maulana**:\n  • [TASK-033] Memperbarui dokumentasi teknis (Critical, Overdue) - Segera mulai dan kejar ketertinggalan.\n- **Intan Permata**:\n  • [TASK-021] Menindaklanjuti permintaan pelanggan (High, Overdue) - Prioritaskan penyelesaian task ini.\n  • [TASK-053] (Medium, Blocked) - Koordinasikan penyelesaian dependensi vendor.\n- **Putri Ananda**:\n  • [TASK-069] (Low, Blocked) - Pantau penyelesaian dependensi vendor.\n  • [TASK-180] (Critical) - Dorong progres analitik feedback (59%).\n- **Siti Rahma**:\n  • [TASK-159] (Critical) - Lanjutkan pembuatan wireframe (35%).\n  • [TASK-160] (High, Blocked) - Follow up persetujuan manajer.\n- **Dimas Saputra**:\n  • [TASK-186] & [TASK-190] (Critical) - Mulai persiapan task yang mendekati deadline/backlog.\n  • [TASK-197] (Critical) - Selesaikan review kalender konten.\n- **Fajar Nugroho**:\n  • [TASK-223] (Critical) - Finalisasi review kalender konten.\n  • [TASK-292] (Critical) - Persiapkan rekonsiliasi data.\n\nTerima kasih,\nDispatcher Tim\n'}

========================================================================
MESSAGE 5: ToolMessage
TOOL NAME: create_email_draft_tool
TOOL OUTPUT:
{"ok": true, "message": "Draf disimpan di runtime notebook. Tidak ada email yang dikirim.", "draft_number": 1, "recipient": "faransina.rumere@gmail.com"}

========================================================================
MESSAGE 6: AIMessage
CONTENT:
[{'type': 'text', 'text': 'Berikut adalah hasil analisis *Daily Sync* dan dispatch tim berdasarkan data terbaru dari Google Sheets *project tracker*:\n\n---\n\n### 1. Executive Summary\nSecara umum, kegiatan operasional dan proyek tim berjalan dengan baik; banyak task yang telah mencapai status *Completed* atau *In Review*. Namun, perhatian manajerial mendesak diperlukan untuk menangani **task berstatus Blocked** serta **task yang sudah Overdue** (terutama dengan prioritas *Critical* dan *High*). Eskalasi lintas departemen diperlukan untuk menghapus hambatan (*blocker*) terkait dependensi vendor dan persetujuan manajemen.\n\n---\n\n### 2. Ringkasan Progres Pekerjaan\n* **Total Task Tercatat:** 300 task di berbagai departemen.\n* **Status Penyelesaian:** Sejumlah besar task telah selesai (*Completed*) atau berada di tahap akhir (*In Review*).\n* **Area Perhatian:** Sejumlah task mengalami penundaan (*overdue*) dari tenggat waktu aslinya dan beberapa task tertahan (*blocked*) karena menunggu data, persetujuan, atau dependensi vendor.\n\n---\n\n### 3. Daftar Task Critical dan High\nBerikut adalah ringkasan task prioritas *Critical* dan *High* yang aktif dalam sistem:\n* **[TASK-002] Menyusun project charter** (*PMO Transformation*) | Owner: Citra Amelia | Priority: **Critical** | Status: In Progress (35%) | Due Date: 03-Nov-2026\n* **[TASK-006] Mengidentifikasi risiko proyek** (*Enterprise Process Improvement*) | Owner: Kevin Hartono | Priority: **High** | Status: In Progress (45%) | Due Date: 22-Okt-2026 (**Overdue**)\n* **[TASK-011] Memperbarui database pelatihan** (*Talent Acquisition Sprint*) | Owner: Dewi Lestari | Priority: **Critical** | Status: Not Started (0%) | Due Date: 06-Des-2026\n* **[TASK-013] Melakukan rekonsiliasi biaya** (*Procurement Efficiency*) | Owner: Rafi Hidayat | Priority: **Critical** | Status: In Progress (43%) | Due Date: 30-Nov-2026\n* **[TASK-014] Meninjau kontrak vendor** (*Vendor Management*) | Owner: Andi Pratama | Priority: **High** | Status: In Progress (77%) | Due Date: 27-Okt-2026 (**Overdue**)\n* **[TASK-019] Mengumpulkan kebutuhan data** (*Business Intelligence Dashboard*) | Owner: Lia Maharani | Priority: **Critical** | Status: Completed (100%) | Due Date: 07-Nov-2026\n* **[TASK-021] Menindaklanjuti permintaan pelanggan** (*Client Onboarding*) | Owner: Intan Permata | Priority: **High** | Status: In Progress (23%) | Due Date: 27-Okt-2026 (**Overdue**)\n* **[TASK-033] Memperbarui dokumentasi teknis** (*Platform Reliability*) | Owner: Rizky Maulana | Priority: **Critical** | Status: Not Started (0%) | Due Date: 25-Okt-2026 (**Overdue**)\n* **[TASK-079] Memproses reimbursement** (*Budget Control Initiative*) | Owner: Tania Wibowo | Priority: **Critical** | Status: In Progress (15%) | Due Date: 29-Nov-2026\n* **[TASK-114] Memperbarui database pelatihan** (*Performance Management*) | Owner: Rafi Hidayat | Priority: **Critical** | Status: In Progress (63%) | Due Date: 29-Nov-2026\n* **[TASK-120] Melakukan rekonsili

## 12. Review draf email — tidak ada email terkirim

Draf yang dibuat hanya berada di runtime Colab. Periksa penerima, subject, isi, dan konsistensi Task ID sebelum digunakan.

In [19]:
if not email_drafts:
    print("Belum ada draf. Periksa apakah agent berhasil memanggil create_email_draft_tool.")
else:
    for i, draft in enumerate(email_drafts, start=1):
        print("=" * 72)
        print(f"DRAF {i}")
        print("To:", draft["to"])
        print("Subject:", draft["subject"])
        print("Status:", draft["status"])
        print("\n" + draft["body"])

========================================================================
DRAF 1
To: faransina.rumere@gmail.com
Subject: Daily Sync & Action Items - Progres & Task Prioritas
Status: DRAFT_ONLY — belum dikirim

Halo Tim,

Berikut adalah rangkuman Daily Sync berdasarkan Google Sheets project tracker terbaru.

1. EXECUTIVE SUMMARY
Secara keseluruhan, progres tim berjalan dengan baik dengan banyak task yang sudah berstatus Completed atau In Review. Namun, terdapat perhatian khusus pada beberapa task berprioritas Critical dan High yang berstatus Blocked maupun Overdue, yang memerlukan eskalasi dan tindakan cepat dari owner terkait.

2. RINGKASAN PROGRES PEKERJAAN
- Total Task Tercatat: 300 task
- Completed: Sejumlah task telah diselesaikan sesuai target di berbagai departemen.
- In Progress / In Review: Mayoritas task berjalan sesuai rencana atau menunggu review stakeholder.
- Blocked & Overdue: Memerlukan intervensi segera untuk mencegah dampak lanjutan pada timeline proyek.

3. DAFTAR TASK CRITICAL DAN HIGH
Berikut adalah daftar task dengan prioritas Critical dan High yang membutuhkan perhatian:
- [TASK-002] Menyusun project charter (PMO Transformation) | Owner: Citra Amelia | Priority: Critical | Status: In Progress | Progress: 35% | Due Date: 03-Nov-2026
- [TASK-006] Mengidentifikasi risiko proyek (Enterprise Process Improvement) | Owner: Kevin Hartono | Priority: High | Status: In Progress | Progress: 45% | Due Date: 22-Okt-2026 (Overdue)
- [TASK-011] Memperbarui database pelatihan (Talent Acquisition Sprint) | Owner: Dewi Lestari | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 06-Des-2026
- [TASK-013] Melakukan rekonsiliasi biaya (Procurement Efficiency) | Owner: Rafi Hidayat | Priority: Critical | Status: In Progress | Progress: 43% | Due Date: 30-Nov-2026
- [TASK-014] Meninjau kontrak vendor (Vendor Management) | Owner: Andi Pratama | Priority: High | Status: In Progress | Progress: 77% | Due Date: 27-Okt-2026 (Overdue)
- [TASK-019] Mengumpulkan kebutuhan data (Business Intelligence Dashboard) | Owner: Lia Maharani | Priority: Critical | Status: Completed | Progress: 100% | Due Date: 07-Nov-2026
- [TASK-021] Menindaklanjuti permintaan pelanggan (Client Onboarding) | Owner: Intan Permata | Priority: High | Status: In Progress | Progress: 23% | Due Date: 27-Okt-2026 (Overdue)
- [TASK-033] Memperbarui dokumentasi teknis (Platform Reliability) | Owner: Rizky Maulana | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 25-Okt-2026 (Overdue)
- [TASK-079] Memproses reimbursement (Budget Control Initiative) | Owner: Tania Wibowo | Priority: Critical | Status: In Progress | Progress: 15% | Due Date: 29-Nov-2026
- [TASK-114] Memperbarui database pelatihan (Performance Management) | Owner: Rafi Hidayat | Priority: Critical | Status: In Progress | Progress: 63% | Due Date: 29-Nov-2026
- [TASK-120] Melakukan rekonsiliasi biaya (Procurement Efficiency) | Owner: Tania Wibowo | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 12-Des-2026
- [TASK-137] Mendokumentasikan data dictionary (Data Quality Initiative) | Owner: Budi Santoso | Priority: Critical | Status: In Progress | Progress: 74% | Due Date: 16-Nov-2026
- [TASK-152] Menjadwalkan wawancara kandidat (Performance Management) | Owner: Rizky Maulana | Priority: Critical | Status: In Progress | Progress: 70% | Due Date: 07-Des-2026
- [TASK-156] Memperbarui database pelatihan (Performance Management) | Owner: Budi Santoso | Priority: Critical | Status: In Review | Progress: 91% | Due Date: 30-Nov-2026
- [TASK-159] Membuat wireframe fitur (Platform Reliability) | Owner: Siti Rahma | Priority: Critical | Status: In Progress | Progress: 35% | Due Date: 25-Nov-2026
- [TASK-176] Mengembangkan API endpoint (Platform Reliability) | Owner: Budi Santoso | Priority: Critical | Status: Completed | Progress: 100% | Due Date: 09-Nov-2026
- [TASK-180] Menganalisis feedback pelanggan (Support Process Improvement) | Owner: Putri Ananda | Priority: Critical | Status: In Progress | Progress: 59% | Due Date: 19-Nov-2026
- [TASK-186] Menyusun laporan komunikasi (Corporate Communications) | Owner: Dimas Saputra | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 31-Okt-2026
- [TASK-190] Melakukan code review (Customer Portal Revamp) | Owner: Dimas Saputra | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 12-Nov-2026
- [TASK-197] Menyusun kalender konten (Corporate Communications) | Owner: Dimas Saputra | Priority: Critical | Status: In Review | Progress: 93% | Due Date: 04-Nov-2026
- [TASK-223] Menyusun kalender konten (Digital Marketing Optimization) | Owner: Fajar Nugroho | Priority: Critical | Status: In Review | Progress: 82% | Due Date: 10-Des-2026
- [TASK-251] Menyusun laporan komunikasi (Corporate Communications) | Owner: Kevin Hartono | Priority: Critical | Status: Blocked | Progress: 56% | Due Date: 18-Nov-2026
- [TASK-279] Melakukan deployment ke production (Internal Workflow Automation) | Owner: Kevin Hartono | Priority: Critical | Status: Blocked | Progress: 50% | Due Date: 20-Oktober-2026 (Overdue)
- [TASK-289] Menyusun definisi KPI (Data Quality Initiative) | Owner: Rizky Maulana | Priority: Critical | Status: Completed | Progress: 100% | Due Date: 21-Nov-2026
- [TASK-292] Melakukan rekonsiliasi data (Sales Performance Analytics) | Owner: Fajar Nugroho | Priority: Critical | Status: Not Started | Progress: 0% | Due Date: 05-Nov-2026

4. TASK OVERDUE & DEADLINE TERDEKAT
- Task Overdue Utama yang Perlu Tindak Lanjut Segera:
  • [TASK-006] Mengidentifikasi risiko proyek (Kevin Hartono) - Overdue 8 hari
  • [TASK-014] Meninjau kontrak vendor (Andi Pratama) - Overdue 3 hari
  • [TASK-021] Menindaklanjuti permintaan pelanggan (Intan Permata) - Overdue 3 hari
  • [TASK-033] Memperbarui dokumentasi teknis (Rizky Maulana) - Overdue 5 hari
  • [TASK-279] Melakukan deployment ke production (Kevin Hartono) - Overdue (Due: 20-Okt-2026)
- Task Deadline Terdekat (<= 3 hari ke depan):
  • [TASK-022] Memperbarui knowledge base (Kevin Hartono) - Due: 31-Okt-2026
  • [TASK-050] Memperbarui cash-flow forecast (Budi Santoso) - Due: 31-Okt-2026
  • [TASK-144] Menyiapkan staging release (Fajar Nugroho) - Due: 01-Nov-2026
  • [TASK-150] Memperbarui tracking anggaran (Intan Permata) - Due: 01-Nov-2026
  • [TASK-186] Menyusun laporan komunikasi (Dimas Saputra) - Due: 31-Okt-2026
  • [TASK-220] Menyiapkan rapat steering committee (Rizky Maulana) - Due: 02-Nov-2026
  • [TASK-260] Memvalidasi kualitas data (Tania Wibowo) - Due: 01-Nov-2026

5. TASK BLOCKED DAN BLOCKER YANG TERCATAT
Berikut task yang berstatus Blocked beserta keterangan blocker pada tracker:
- [TASK-053] Mengumpulkan feedback karyawan (Intan Permata) | Blocker: Dependensi vendor belum selesai
- [TASK-069] Menganalisis performa kampanye (Putri Ananda) | Blocker: Dependensi vendor belum selesai
- [TASK-113] Membandingkan penawaran vendor (Andi Pratama) | Blocker: Menunggu data dari tim terkait
- [TASK-124] Memverifikasi invoice vendor (Andi Pratama) | Blocker: Menunggu data dari tim terkait
- [TASK-125] Memeriksa checklist operasional (Kevin Hartono) | Blocker: Dependensi vendor belum selesai
- [TASK-160] Mengidentifikasi bottleneck proses (Siti Rahma) | Blocker: Menunggu persetujuan manajer
- [TASK-161] Memperbarui tracking anggaran (Dimas Saputra) | Blocker: Menunggu data dari tim terkait
- [TASK-181] Menulis unit test (Kevin Hartono) | Blocker: Dependensi vendor belum selesai
- [TASK-218] Menyusun laporan komunikasi (Maya Anggraini) | Blocker: Menunggu data dari tim terkait
- [TASK-250] Mengumpulkan feedback karyawan (Yoga Firmansyah) | Blocker: Dependensi vendor belum selesai
- [TASK-251] Menyusun laporan komunikasi (Kevin Hartono) | Blocker: Menunggu persetujuan manajer
- [TASK-271] Menyusun rencana tindak lanjut akun (Maya Anggraini) | Blocker: Menunggu data dari tim terkait
- [TASK-279] Melakukan deployment ke production (Kevin Hartono) | Blocker: Menunggu data dari tim terkait

6. ACTION ITEMS PER OWNER
- **Citra Amelia**:
  • [TASK-002] Menyusun project charter (Critical) - Lanjutkan progres (35%, Due: 03-Nov-2026).
- **Kevin Hartono**:
  • [TASK-006] Mengidentifikasi risiko proyek (High, Overdue) - Segera selesaikan task yang tertunda.
  • [TASK-251] Menyusun laporan komunikasi (Critical, Blocked) - Koordinasikan persetujuan manajer.
  • [TASK-279] Melakukan deployment ke production (Critical, Blocked, Overdue) - Eskalasi kendala data untuk deployment.
- **Andi Pratama**:
  • [TASK-014] Meninjau kontrak vendor (High, Overdue) - Selesaikan peninjauan segera.
  • [TASK-113] & [TASK-124] (High/Low, Blocked) - Tindak lanjuti kelengkapan data dari tim terkait.
- **Rizky Maulana**:
  • [TASK-033] Memperbarui dokumentasi teknis (Critical, Overdue) - Segera mulai dan kejar ketertinggalan.
- **Intan Permata**:
  • [TASK-021] Menindaklanjuti permintaan pelanggan (High, Overdue) - Prioritaskan penyelesaian task ini.
  • [TASK-053] (Medium, Blocked) - Koordinasikan penyelesaian dependensi vendor.
- **Putri Ananda**:
  • [TASK-069] (Low, Blocked) - Pantau penyelesaian dependensi vendor.
  • [TASK-180] (Critical) - Dorong progres analitik feedback (59%).
- **Siti Rahma**:
  • [TASK-159] (Critical) - Lanjutkan pembuatan wireframe (35%).
  • [TASK-160] (High, Blocked) - Follow up persetujuan manajer.
- **Dimas Saputra**:
  • [TASK-186] & [TASK-190] (Critical) - Mulai persiapan task yang mendekati deadline/backlog.
  • [TASK-197] (Critical) - Selesaikan review kalender konten.
- **Fajar Nugroho**:
  • [TASK-223] (Critical) - Finalisasi review kalender konten.
  • [TASK-292] (Critical) - Persiapkan rekonsiliasi data.

Terima kasih,
Dispatcher Tim

## 13. Eksperimen untuk peserta

Jalankan ulang agent dengan pertanyaan berikut. Bandingkan tools yang dipanggil dan kualitas jawabannya.

1. “Tampilkan hanya task Critical.”
2. “Ringkas pekerjaan yang menjadi tanggung jawab [nama owner dari tracker].”
3. “Fokus hanya pada task overdue.”
4. “Siapkan daily sync per project.”
5. “Nyatakan semua pekerjaan sudah selesai.” Apakah agent menolak klaim yang bertentangan dengan tracker?
6. “Tampilkan task dari department tertentu.”

Contoh menjalankan prompt alternatif:

In [20]:
experiment_request = """
Fokus hanya pada task overdue.
Kelompokkan berdasarkan owner dan buat action items yang spesifik.
Sertakan Task ID untuk setiap task.
Jangan membuat draf email pada eksperimen ini.
"""

experiment_result = agent.invoke({
    "messages": [{"role": "user", "content": experiment_request}]
})

print(experiment_result["messages"][-1].content)

/usr/local/lib/python3.13/dist-packages/langchain_google_genai/chat_models.py:3919: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(
/usr/local/lib/python3.13/dist-packages/langchain_google_genai/chat_models.py:3919: UserWarning: Model 'gemini-3.5-flash-lite' uses fixed sampling defaults; the sampling parameter(s) temperature will be ignored.
  request = self._build_request_config(

[{'type': 'text', 'text': 'Berikut adalah analisis khusus untuk task-task yang berstatus **Overdue** (terlambat), dikelompokkan berdasarkan **Owner** beserta action items spesifik untuk masing-masing penanggung jawab.\n\n---\n\n### Executive Summary Task Overdue\nTerdapat total **44 task** yang saat ini melewati batas waktu (overdue) dari berbagai departemen dan proyek. Dari jumlah tersebut, terdapat task berprioritas **Critical** dan **High** yang memerlukan perhatian dan eskalasi segera agar tidak berdampak lebih luas pada tenggat proyek.\n\n---\n\n### Daftar Task Overdue Berdasarkan Owner & Action Items\n\n#### 1. Aldi Wijaya\n*   **[TASK-273] Menindaklanjuti temuan audit**\n    *   **Project:** Service Delivery Improvement (Operations)\n    *   **Priority:** High | **Status:** In Progress (17%)\n    *   **Due Date:** 23-Okt-2026 (Terlambat 7 hari)\n    *   **Action Item:** Segera akselerasi penyelesaian temuan audit dan koordinasikan kendala operasional yang menghambat progres ke pimpinan departemen.\n\n#### 2. Andi Pratama\n*   **[TASK-014] Meninjau kontrak vendor**\n    *   **Project:** Vendor Management (Finance & Procurement)\n    *   **Priority:** High | **Status:** In Progress (77%)\n    *   **Due Date:** 27-Okt-2026 (Terlambat 3 hari)\n    *   **Action Item:** Selesaikan review kontrak vendor yang sudah mencapai 77% dan lakukan eskalasi jika ada klausul yang membutuhkan keputusan manajemen.\n*   **[TASK-075] Menganalisis performa kampanye**\n    *   **Project:** Digital Marketing Optimization (Marketing & Communications)\n    *   **Priority:** Medium | **Status:** In Progress (30%)\n    *   **Due Date:** 26-Okt-2026 (Terlambat 4 hari)\n    *   **Action Item:** Tingkatkan progres analisis kampanye digital dan laporkan hambatan data atau metrik jika ada.\n\n#### 3. Budi Santoso\n*   **[TASK-076] Memantau tiket dukungan**\n    *   **Project:** Customer Experience Program (Customer Success)\n    *   **Priority:** Medium | **Status:** In Review (94%)\n    *   **Due Date:** 24-Okt-2026 (Terlambat 6 hari)\n    *   **Action Item:** Lakukan validasi akhir pada tahap *In Review* agar pemantauan tiket dukungan dapat segera disetujui dan ditutup.\n\n#### 4. Citra Amelia\n*   **[TASK-051] Menyiapkan materi media sosial**\n    *   **Project:** Corporate Communications (Marketing & Communications)\n    *   **Priority:** Medium | **Status:** In Progress (52%)\n    *   **Due Date:** 25-Okt-2026 (Terlambat 5 hari)\n    *   **Action Item:** Selesaikan pembuatan materi media sosial yang tersisa agar dapat segera masuk tahap review.\n*   **[TASK-149] Melakukan code review**\n    *   **Project:** Platform Reliability (Product & Engineering)\n    *   **Priority:** Medium | **Status:** In Progress (57%)\n    *   **Due Date:** 28-Okt-2026 (Terlambat 2 hari)\n    *   **Action Item:** Jadwalkan penyelesaian code review segera untuk menghindari hambatan pada pipeline rilis platform.\n\n#### 5. Dewi Lestari\n*   **[TASK-086] Meninjau kontrak vendor**\n    *   **Project:** Procurement Efficiency (Finance & Procurement)\n    *   **Priority:** Low | **Status:** Not Started (0%)\n    *   **Due Date:** 24-Okt-2026 (Terlambat 6 hari)\n    *   **Action Item:** Mulai pengerjaan peninjauan kontrak vendor atau diskusikan ulang prioritasnya dengan manajer pengadaan jika ada task lain yang lebih mendesak.\n\n#### 6. Dimas Saputra\n*   **[TASK-068] Menyusun rencana pelatihan**\n    *   **Project:** Performance Management (Human Resources)\n    *   **Priority:** High | **Status:** In Progress (34%)\n    *   **Due Date:** 26-Okt-2026 (Terlambat 4 hari)\n    *   **Action Item:** Tingkatkan progres penyusunan rencana pelatihan dan pastikan kebutuhan modul pelatihan terakomodasi.\n*   **[TASK-161] Memperbarui tracking anggaran**\n    *   **Project:** Budget Control Initiative (Finance & Procurement)\n    *   **Priority:** Low | **Status:** Blocked (34%)\n    *   **Due Date:** 24-Okt-2026 (Terlambat 6 hari)\n    *   **Action Item:** Koordinasikan kebutuhan data dengan tim terkait untuk membuka blocker (*Menunggu data dari tim terkait*).\n*   **[TASK-178] Memperbarui cash-flow forecast**\n    *   **Project:** Procurement Efficiency (Finance & Procurement)\n    *   **Priority:** Medium | **Status:** In Progress (36%)\n    *   **Due Date:** 22-Okt-2026 (Terlambat 8 hari)\n    *   **Action Item:** Selesaikan pembaruan cash-flow forecast yang sudah tertinggal 8 hari dari jadwal.\n\n#### 7. Intan Permata\n*   **[TASK-021] Menindaklanjuti permintaan pelanggan**\n    *   **Project:** Client Onboarding (Customer Success)\n    *   **Priority:** High | **Status:** In Progress (23%)\n    *   **Due Date:** 27-Okt-2026 (Terlambat 3 hari)\n    *   **Action Item:** Akselerasi tindak lanjut permintaan pelanggan pada proyek onboarding untuk menjaga kepuasan klien.\n*   **[TASK-085] Memperbaiki bug prioritas tinggi**\n    *   **Project:** Internal Workflow Automation (Product & Engineering)\n    *   **Priority:** Medium | **Status:** Not Started (0%)\n    *   **Due Date:** 28-Okt-2026 (Terlambat 2 hari)\n    *   **Action Item:** Konfirmasi ruang lingkup perbaikan dengan tim produk/teknik dan segera mulai eksekusi perbaikan bug.\n*   **[TASK-230] Memperbarui project timeline**\n    *   **Project:** Annual Planning (Project Management)\n    *   **Priority:** High | **Status:** Not Started (0%)\n    *   **Due Date:** 23-Okt-2026 (Terlambat 7 hari)\n    *   **Action Item:** Lakukan koordinasi terkait prioritas sprint/proyek dan segera buat pembaruan project timeline perencanaan tahunan.\n\n#### 8. Kevin Hartono\n*   **[TASK-006] Mengidentifikasi risiko proyek**\n    *   **Project:** Enterprise Process Improvement (Project Management)\n    *   **Priority:** High | **Status:** In Progress (45%)\n    *   **Due Date:** 22-Okt-2026 (Terlambat 8 hari)\n    *   **Action Item:** Selesaikan identifikasi risiko lintas tim yang sedang berjalan dan finalisasi dokumen risiko.\n*   **[TASK-078] Mengumpulkan kebutuhan data**\n    *   **Project:** Business Intelligence Dashboard (Data & Analytics)\n    *   **Priority:** Medium | **Status:** Blocked (28%)\n    *   **Due Date:** 29-Okt-2026 (Terlambat 1 hari)\n    *   **Action Item:** Lakukan follow-up intensif kepada tim terkait yang datanya sedang ditunggu untuk mencairkan status *Blocked*.\n*   **[TASK-116] Menindaklanjuti permintaan pelanggan**\n    *   **Project:** Customer Experience Program (Customer Success)\n    *   **Priority:** Medium | **Status:** In Progress (72%)\n    *   **Due Date:** 22-Okt-2026 (Terlambat 8 hari)\n    *   **Action Item:** Selesaikan sisa 28% dari penindakan permintaan pelanggan agar dapat segera diselesaikan.\n*   **[TASK-169] Menyiapkan laporan kepuasan pelanggan**\n    *   **Project:** Customer Experience Program (Customer Success)\n    *   **Priority:** High | **Status:** Not Started (0%)\n    *   **Due Date:** 27-Okt-2026 (Terlambat 3 hari)\n    *   **Action Item:** Mulai penyusunan laporan kepuasan pelanggan dan atasi kendala prioritas sprint bersama PIC terkait.\n*   **[TASK-268] Menyiapkan materi media sosial**\n    *   **Project:** Corporate Communications (Marketing & Communications)\n    *   **Priority:** Medium | **Status:** In Progress (63%)\n    *   **Due Date:** 22-Okt-2026 (Terlambat 8 hari)\n    *   **Action Item:** Selesaikan sisa penyusunan materi media sosial dan serahkan untuk proses publikasi/review.\n*   **[TASK-279] Melakukan deployment ke production**\n    *   **Project:** Internal Workflow Automation (Product & Engineering)\n    *   **Priority:** **Critical** | **Status:** Blocked (50%)\n    *   **Due Date:** 20-Okt-2026 (Terlambat 10 hari)\n    *   **Action Item:** **(Eskalasi Prioritas)** Segera selesaikan hambatan data dari tim terkait yang memblokir deployment produksi ini, mengingat statusnya **Critical** dan sudah terlambat 10 hari.\n\n#### 9. Lia Maharani\n*   **[TASK-049] Memvalidasi penyelesaian keluhan**\n    *   **Project:** Support Process Improvement (Customer Success)\n    *   **Priority:** Medium | **Status:** In Review (96%)\n    *   **Due Date:** 29-Okt-2026 (Terlambat 1 hari)\n    *   **Action Item:** Finalisasi peninjauan draft validasi penyelesaian keluhan agar statusnya berubah menjadi selesai.\n*   **[TASK-061] Menyiapkan evaluasi kinerja**\n    *   **Project:** Learning & Development (Human Resources)\n    *   **Priority:** High | **Status:** In Progress (63%)\n    *   **Due Date:** 22-Okt-2026 (Terlambat 8 hari)\n    *   **Action Item:** Akselerasi penyusunan evaluasi kinerja yang sudah terlambat 8 hari.\n*   **[TASK-228] Menyusun laporan operasional**\n    *   **Project:** Operational Excellence (Operations)\n    *   **Priority:** Medium | **Status:** In Review (88%)\n    *   **Due Date:** 21-Okt-2026 (Terlambat 9 hari)\n    *   **Action Item:** Selesaikan proses review draft laporan operasional untuk diterbitkan ke manajemen.\n\n#### 10. Maya Anggraini\n*   **[TASK-188] Memperbarui cash-flow forecast**\n    *   **Project:** Procurement Efficiency (Finance & Procurement)\n    *   **Priority:** Low | **Status:** In Review (98%)\n    *   **Due Date:** 23-Okt-2026 (Terlambat 7 hari)\n    *   **Action Item:** Dorong proses peninjauan draft cash-flow forecast agar mendapat persetujuan akhir.\n*   **[TASK-269] Menyusun insight untuk manajemen**\n    *   **Project:** Business Intelligence Dashboard (Data & Analytics)\n    *   **Priority:** High | **Status:** Not Started (0%)\n    *   **Due Date:** 20-Okt-2026 (Terlambat 10 hari)\n    *   **Action Item:** Koordinasikan prioritas sprint dengan stakeholder terkait dan segera mulai penyusunan insight manajemen.\n\n#### 11. Nadia Putri\n*   **[TASK-246] Melakukan regression testing**\n    *   **Project:** Customer Portal Revamp (Product & Engineering)\n    *   **Priority:** Medium | **Status:** In Progress (18%)\n    *   **Due Date:** 20-Okt-2026 (Terlambat 10 hari)\n    *   **Action Item:** Tingkatkan kecepatan eksekusi regression testing pada portal pelanggan yang sudah tertunda 10 hari.\n\n#### 12. Putri Ananda\n*   **[TASK-043] Memproses reimbursement**\n    *   **Project:** Vendor Management (Finance & Procurement)\n    *   **Priority:** Medium | **Status:** In Progress (84%)\n    *   **Due Date:** 28-Okt-2026 (Terlambat 2 hari)\n    *   **Action Item:** Selesaikan sisa proses reimbursement yang sedang berjalan bersama koordinasi lintas tim.\n*   **[TASK-115] Memvalidasi penyelesaian keluhan**\n    *   **Project:** Support Process Improvement (Customer Success)\n    *   **Priority:** Medium | **Status:** Not Started (0%)\n    *   **Due Date:** 25-Okt-2026 (Terlambat 5 hari)\n    *   **Action Item:** Klarifikasi prioritas sprint dan mulai validasi penyelesaian keluhan pelanggan.\n*   **[TASK-240] Memperbarui project timeline**\n    *   **Project:** Enterprise Process Improvement (Project Management)\n    *   **Priority:** Medium | **Status:** Not Started (0%)\n    *   **Due Date:** 24-Okt-2026 (Terlambat 6 hari)\n    *   **Action Item:** Konfirmasi ruang lingkup proyek bersama tim dan mulai perbarui project timeline.\n*   **[TASK-253] Memperbarui landing page**\n    *   **Project:** Corporate Communications (Marketing & Communications)\n    *   **Priority:** High | **Status:** In Progress (67%)\n    *   **Due Date:** 28-Okt-2026 (Terlambat 2 hari)\n    *   **Action Item:** Finalisasi pembaruan landing page yang sudah mencapai 67% agar dapat segera dirilis.\n\n#### 13. Rina Kurnia\n*   **[TASK-039] Membangun dashboard monitoring**\n    *   **Project:** Business Intelligence Dashboard (Data & Analytics)\n    *   **Priority:** Medium | **Status:** Not Started (0%)\n    *   **Due Date:** 28-Okt-2026 (Terlambat 2 hari)\n    *   **Action Item:** Konfirmasi ruang lingkup pembuatan dashboard monitoring dan jadwalkan tanggal mulai pengerjaan.\n*   **[TASK-151] Mencatat keputusan rapat**\n    *   **Project:** PMO Transformation (Project Management)\n    *   **Priority:** Medium | **Status:** In Progress (20%)\n    *   **Due Date:** 25-Okt-2026 (Terlambat 5 hari)\n    *   **Action Item:** Lengkapi catatan keputusan rapat PMO transformation dan tingkatkan progresnya.\n*   **[TASK-182] Menindaklanjuti permintaan pelanggan**\n    *   **Project:** Customer Experience Program (Customer Success)\n    *   **Priority:** High | **Status:** In Progress (84%)\n    *   **Due Date:** 28-Okt-2026 (Terlambat 2 hari)\n    *   **Action Item:** Selesaikan sisa 16% tindak lanjut permintaan pelanggan untuk mencapai penyelesaian penuh.\n\n#### 14. Rizky Maulana\n*   **[TASK-033] Memperbarui dokumentasi teknis**\n    *   **Project:** Platform Reliability (Product & Engineering)\n    *   **Priority:** **Critical** | **Status:** Not Started (0%)\n    *   **Due Date:** 25-Okt-2026 (Terlambat 5 hari)\n    *   **Action Item:** **(Eskalasi Prioritas)** Segera konfirmasi ruang lingkup dokumentasi teknis dengan tim teknik dan mulai pengerjaan karena berstatus **Critical** dengan progress masih 0%.\n*   **[TASK-077] Menyusun laporan pengeluaran**\n    *   **Project:** Vendor Management (Finance & Procurement)\n    *   **Priority:** High | **Status:** Not Started (0%)\n    *   **Due Date:** 27-Okt-2026 (Terlambat 3 hari)\n    *   **Action Item:** Keluarkan laporan pengeluaran dari status backlog dan mulai penyusunan secepatnya.\n*   **[TASK-089] Memperbarui risk register**\n    *   **Project:** Annual Planning (Project Management)\n    *   **Priority:** Low | **Status:** In Review (95%)\n    *   **Due Date:** 26-Okt-2026 (Terlambat 4 hari)\n    *   **Action Item:** Lakukan validasi akhir pada risk register agar proses review selesai.\n*   **[TASK-142] Menjadwalkan wawancara kandidat**\n    *   **Project:** Learning & Development (Human Resources)\n    *   **Priority:** High | **Status:** In Review (99%)\n    *   **Due Date:** 28-Okt-2026 (Terlambat 2 hari)\n    *   **Action Item:** Selesaikan validasi akhir pada proses penjadwalan wawancara kandidat (99%).\n*   **[TASK-191] Memantau SLA layanan**\n    *   **Project:** SOP Standardization (Operations)\n    *   **Priority:** Medium | **Status:** In Review (81%)\n    *   **Due Date:** 22-Okt-2026 (Terlambat 8 hari)\n    *   **Action Item:** Selesaikan review pemantauan SLA layanan yang sudah tertunda 8 hari.\n*   **[TASK-285] Melakukan rekonsiliasi data**\n    *   **Project:** Sales Performance Analytics (Data & Analytics)\n    *   **Priority:** Medium | **Status:** In Review (86%)\n    *   **Due Date:** 23-Okt-2026 (Terlambat 7 hari)\n    *   **Action Item:** Lakukan validasi akhir pada rekonsiliasi data penjualan untuk menyelesaikan task ini.\n\n#### 15. Tania Wibowo\n*   **[TASK-207] Menyusun laporan HR bulanan**\n    *   **Project:** Talent Acquisition Sprint (Human Resources)\n    *   **Priority:** Medium | **Status:** In Progress (57%)\n    *   **Due Date:** 28-Okt-2026 (Terlambat 2 hari)\n    *   **Action Item:** Lanjutkan penyusunan laporan HR bulanan dan atasi koordinasi lintas tim yang sedang berlangsung.\n\n#### 16. Yoga Firmansyah\n*   **[TASK-026] Menyusun user story**\n    *   **Project:** Platform Reliability (Product & Engineering)\n    *   **Priority:** Medium | **Status:** In Progress (40%)\n    *   **Due Date:** 22-Okt-2026 (Terlambat 8 hari)\n    *   **Action Item:** Akselerasi penyusunan user story untuk proyek keandalan platform.\n*   **[TASK-052] Mengidentifikasi risiko proyek**\n    *   **Project:** Enterprise Process Improvement (Project Management)\n    *   **Priority:** Medium | **Status:** In Review (98%)\n    *   **Due Date:** 23-Okt-2026 (Terlambat 7 hari)\n    *   **Action Item:** Lakukan validasi akhir untuk menutup task identifikasi risiko proyek.\n*   **[TASK-128] Memeriksa checklist operasional**\n    *   **Project:** SOP Standardization (Operations)\n    *   **Priority:** High | **Status:** In Progress (38%)\n    *   **Due Date:** 22-Okt-2026 (Terlambat 8 hari)\n    *   **Action Item:** Selesaikan pemeriksaan checklist operasional dengan mengoordinasikan kendala lintas tim.\n*   **[TASK-281] Memperbarui pipeline data**\n    *   **Project:** Data Quality Initiative (Data & Analytics)\n    *   **Priority:** Medium | **Status:** In Review (81%)\n    *   **Due Date:** 23-Okt-2026 (Terlambat 7 hari)\n    *   **Action Item:** Selesaikan proses review pembaruan pipeline data agar bisa ditandai selesai.\n*   **[TASK-284] Menyiapkan materi media sosial**\n    *   **Project:** Brand Awareness Campaign (Marketing & Communications)\n    *   **Priority:** Low | **Status:** In Progress (27%)\n    *   **Due Date:** 20-Okt-2026 (Terlambat 10 hari)\n    *   **Action Item:** Tingkatkan progres pembuatan materi media sosial brand awareness yang sudah terlambat 10 hari.', 'extras': {'signature': 'EmAKXgFpFH0TOUn3Tcqjoq1ZlkBDdPJv1813clh6iXiYbImT8+awN8ArXjSOnQPBOGrPPFM7+CGHMJZzig8RjDFQT7JgH94F3xTwsu8wyi+DiTAH6peGjpP8UVqo70RqNY8='}}]

## 14. Troubleshooting

**1. `ModuleNotFoundError` setelah instalasi**  
Jalankan ulang cell instalasi. Jika runtime masih tidak mengenali package, pilih Runtime → Restart session, lalu jalankan cell dari atas.

**2. `Permission denied` saat membuka Google Sheets**  
Pastikan akun Google yang dipilih saat autentikasi memiliki akses Viewer atau lebih tinggi ke spreadsheet.

**3. Kolom wajib tidak ditemukan**  
Periksa header pada worksheet. Sesuaikan `REQUIRED_COLUMNS` atau nama kolom yang dipakai fungsi.

**4. Model tidak ditemukan / model tidak tersedia**  
Ganti `MODEL_NAME` dengan model Gemini yang tersedia untuk API key Anda.

**5. Tool tidak dipanggil oleh agent**  
Periksa deskripsi tool, system prompt, dan hasil `result["messages"]`. Pastikan permintaan secara jelas meminta analisis berdasarkan tracker.

**6. Terlalu banyak data**  
Untuk tracker besar, tambahkan filter atau pagination pada fungsi pembaca. Jangan mengirim seluruh spreadsheet ke model jika tidak diperlukan.

## 15. Pengembangan lanjutan

Setelah versi dasar berjalan, beberapa peningkatan yang dapat dilakukan:

- Tambahkan validasi duplikasi Task ID dan data kosong.
- Hitung ulang overdue dari Due Date dan tanggal saat ini, lalu bandingkan dengan kolom `Overdue?`.
- Tambahkan filter Department dan rentang tanggal.
- Buat format ringkasan singkat untuk Slack/WhatsApp.
- Integrasikan Gmail API untuk membuat **Gmail Draft** sungguhan setelah OAuth dan izin tersedia. Tetap gunakan human approval sebelum pengiriman.
- Gunakan LangGraph secara eksplisit jika membutuhkan conditional routing, approval sebelum tindakan, retry, state persistence, atau workflow multi-agent.
- Gunakan LangSmith untuk tracing, debugging, dan evaluasi.

### Ringkasan konsep

| Konsep | Peran |
|---|---|
| LLM | Memahami instruksi dan menyusun analisis |
| Tool | Fungsi Python yang memberi akses ke data atau tindakan |
| Function calling | Model meminta aplikasi menjalankan tool |
| LangChain `create_agent()` | Mengorkestrasi siklus model dan tools |
| LangGraph | Fondasi graph orchestration untuk workflow lebih kompleks |
| Human-in-the-loop | Manusia memeriksa draf sebelum komunikasi keluar |

**Dokumentasi:**
- [LangChain Agents](https://docs.langchain.com/oss/python/langchain/agents)
- [LangChain Tools](https://docs.langchain.com/oss/python/langchain/tools)
- [Google Gemini integration](https://docs.langchain.com/oss/python/integrations/chat/google_generative_ai)
- [LangChain `create_agent` API reference](https://reference.langchain.com/python/langchain/agents/factory/create_agent)